package pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage;

/**
* pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCartPackage/ProductUnavailableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* pi¹tek, 29 czerwca 2018 21:56:28 CEST
*/

public final class ProductUnavailableHolder implements org.omg.CORBA.portable.Streamable
{
  public pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailable value = null;

  public ProductUnavailableHolder ()
  {
  }

  public ProductUnavailableHolder (pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailableHelper.type ();
  }

}
