package pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage;


/**
* pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCartPackage/ProductUnavailableHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* pi¹tek, 29 czerwca 2018 21:56:28 CEST
*/

abstract public class ProductUnavailableHelper
{
  private static String  _id = "IDL:pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCart/ProductUnavailable:1.0";

  public static void insert (org.omg.CORBA.Any a, pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailable that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailable extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [0];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailableHelper.id (), "ProductUnavailable", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailable read (org.omg.CORBA.portable.InputStream istream)
  {
    pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailable value = new pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailable ();
    // read and discard the repository ID
    istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailable value)
  {
    // write the repository ID
    ostream.write_string (id ());
  }

}
