package pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage;


/**
* pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCartPackage/ProductUnavailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* pi¹tek, 29 czerwca 2018 21:56:28 CEST
*/

public final class ProductUnavailable extends org.omg.CORBA.UserException
{

  public ProductUnavailable ()
  {
    super(ProductUnavailableHelper.id());
  } // ctor


  public ProductUnavailable (String $reason)
  {
    super(ProductUnavailableHelper.id() + "  " + $reason);
  } // ctor

} // class ProductUnavailable
