package pl.edu.pjwstk.s17504.ShoppingCart;


/**
* pl/edu/pjwstk/s17504/ShoppingCart/_ShoppingCartImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* pi¹tek, 29 czerwca 2018 21:56:28 CEST
*/

public abstract class _ShoppingCartImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCart, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ShoppingCartImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_cart_items", new java.lang.Integer (0));
    _methods.put ("_get_getProducts", new java.lang.Integer (1));
    _methods.put ("addProductToCart", new java.lang.Integer (2));
    _methods.put ("newProduct", new java.lang.Integer (3));
    _methods.put ("removeProduct", new java.lang.Integer (4));
    _methods.put ("changeProductAmount", new java.lang.Integer (5));
    _methods.put ("checkOut", new java.lang.Integer (6));
    _methods.put ("find_product", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCart/_get_cart_items
       {
         pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartItem $result[] = null;
         $result = this.cart_items ();
         out = $rh.createReply();
         pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartItemsHelper.write (out, $result);
         break;
       }

       case 1:  // pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCart/_get_getProducts
       {
         pl.edu.pjwstk.s17504.ShoppingCart.Product $result[] = null;
         $result = this.getProducts ();
         out = $rh.createReply();
         pl.edu.pjwstk.s17504.ShoppingCart.ProductsHelper.write (out, $result);
         break;
       }

       case 2:  // pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCart/addProductToCart
       {
         pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartItem cart_items = pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartItemHelper.read (in);
         this.addProductToCart (cart_items);
         out = $rh.createReply();
         break;
       }

       case 3:  // pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCart/newProduct
       {
         int id = in.read_long ();
         String name = in.read_string ();
         int amountOfStock = in.read_long ();
         pl.edu.pjwstk.s17504.ShoppingCart.Product $result = null;
         $result = this.newProduct (id, name, amountOfStock);
         out = $rh.createReply();
         pl.edu.pjwstk.s17504.ShoppingCart.ProductHelper.write (out, $result);
         break;
       }

       case 4:  // pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCart/removeProduct
       {
         int id = in.read_long ();
         this.removeProduct (id);
         out = $rh.createReply();
         break;
       }

       case 5:  // pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCart/changeProductAmount
       {
         pl.edu.pjwstk.s17504.ShoppingCart.Product product = pl.edu.pjwstk.s17504.ShoppingCart.ProductHelper.read (in);
         int amountOfStock = in.read_long ();
         this.changeProductAmount (product, amountOfStock);
         out = $rh.createReply();
         break;
       }

       case 6:  // pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCart/checkOut
       {
         this.checkOut ();
         out = $rh.createReply();
         break;
       }

       case 7:  // pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCart/find_product
       {
         try {
           int id = in.read_long ();
           pl.edu.pjwstk.s17504.ShoppingCart.Product $result = null;
           $result = this.find_product (id);
           out = $rh.createReply();
           pl.edu.pjwstk.s17504.ShoppingCart.ProductHelper.write (out, $result);
         } catch (pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailable $ex) {
           out = $rh.createExceptionReply ();
           pl.edu.pjwstk.s17504.ShoppingCart.ShoppingCartPackage.ProductUnavailableHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCart:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ShoppingCartImplBase
