package pl.edu.pjwstk.s17504.ShoppingCart;

/**
* pl/edu/pjwstk/s17504/ShoppingCart/ProductHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* pi¹tek, 29 czerwca 2018 21:56:28 CEST
*/

public final class ProductHolder implements org.omg.CORBA.portable.Streamable
{
  public pl.edu.pjwstk.s17504.ShoppingCart.Product value = null;

  public ProductHolder ()
  {
  }

  public ProductHolder (pl.edu.pjwstk.s17504.ShoppingCart.Product initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pl.edu.pjwstk.s17504.ShoppingCart.ProductHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pl.edu.pjwstk.s17504.ShoppingCart.ProductHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pl.edu.pjwstk.s17504.ShoppingCart.ProductHelper.type ();
  }

}
