package pl.edu.pjwstk.s17504.ShoppingCart;


/**
* pl/edu/pjwstk/s17504/ShoppingCart/ShoppingCartItem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* pi¹tek, 29 czerwca 2018 21:56:28 CEST
*/

public final class ShoppingCartItem implements org.omg.CORBA.portable.IDLEntity
{
  public int amount = (int)0;
  public pl.edu.pjwstk.s17504.ShoppingCart.Product product = null;

  public ShoppingCartItem ()
  {
  } // ctor

  public ShoppingCartItem (int _amount, pl.edu.pjwstk.s17504.ShoppingCart.Product _product)
  {
    amount = _amount;
    product = _product;
  } // ctor

} // class ShoppingCartItem
